### ISSUE TITLE
Please triple quote variables

### ISSUE THREAD

**Issue by octoploid** [piotryordanov/fzf-mpd#1]
Thanks for the plugin.
Please triple quote the variables, e.g. `"""$song"""`. 
Otherwise something like "(1999) Vibrant Forms [CRD-07] FLAC/01 - Lark.flac" doesn't get played.

Also please let the user add custom mpc options like "-q -h 192.168.1.2 -p 55555".

**Comment by piotryordanov** [comment]
I'm not sure the triple quote affectes the search. I did create a file with the same name and I can find it.
<img width="1440" alt="screen shot 2017-10-19 at 3 46 45 pm" src="https://user-images.githubusercontent.com/753950/31762220-b9549f34-b4e4-11e7-810c-f8bbe0a59f0a.png">

I think the problem has to do with the fact that this file has no metadata attached to it meaning that `mpc search any` does not return such files. 

To be on the safe side, if you manually search for the file by grepping the result of `mpc search any`, are u able to find it?

- - - -

Regrading adding options, i'd be happy to do that, however I need to figure out how to. So, do you want this option to be passed as a default in kind of a config file, or do you want the options to be passed in something like: `fm -q -h 192.168.1.2 -p 5555` ?

Thx for opening the issue mate!

**Comment by octoploid** [comment]
1) Yes, search works fine, but it fails without triple quotes when running for example "mpc add $song" in fms().

2) A simple variable in the script, that I could edit by hand, would be enough for me.

**Comment by piotryordanov** [comment]
```
# Search for any Song
fms() {
  local song
  song=$(mpc search any "" | \
    fzf-tmux --query="$1" --reverse --select-1 --exit-0) || return 1
  mpc clear;
  [ -n "$song" ] && mpc add """$song"""; mpc play; mpc next
  fm
}
```

I'm assuming that would solve the problem?

- - - -

It can be a global var that ud add to ur zshrc, like `$FMOPTS`. How does that sound?

**Comment by octoploid** [comment]
Yes, this fixes the issue.

A global $FMOPTS var sounds fine.
Thanks.

**Comment by piotryordanov** [comment]
Done. 

```
antigen update
fm -q -h 192.168.1.2 -p 55555
```

I figured it's easier if you can directly pass the options with the command. At least this way, u can even alias it.

Lemme know if the problems are fixed!

**Comment by octoploid** [comment]
Yes. Looks good now. Many thanks.

**Comment by piotryordanov** [comment]
Cheers!
